/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : Purge
 #	author : miyako
 #	2017/11/22
 #
 # --------------------------------------------------------------------------------*/

#include <ServiceManagement/ServiceManagement.h>
#include "HelperTool.h"
#include "libjson.h"

void setup_helper_tool();
void disconnect_from_helper_tool();

// --- Purge
void PURGE_DISK_CACHE(sLONG_PTR *pResult, PackagePtr pParams);
