/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.cpp
 #	source generated by 4D Plugin Wizard
 #	Project : Purge
 #	author : miyako
 #	2014/11/12
 #
 # --------------------------------------------------------------------------------*/


#include "4DPluginAPI.h"
#include "4DPlugin.h"

void PluginMain(PA_long32 selector, PA_PluginParameters params)
{
	try
	{
		PA_long32 pProcNum = selector;
		sLONG_PTR *pResult = (sLONG_PTR *)params->fResult;
		PackagePtr pParams = (PackagePtr)params->fParameters;

		CommandDispatcher(pProcNum, pResult, pParams); 
	}
	catch(...)
	{

	}
}

void CommandDispatcher (PA_long32 pProcNum, sLONG_PTR *pResult, PackagePtr pParams)
{
	switch(pProcNum)
	{

// --- Purge

		case 1 :
			PURGE_DISK_BUFFERS(pResult, pParams);
			break;

	}
}

// ------------------------------------- Purge ------------------------------------


void PURGE_DISK_BUFFERS(sLONG_PTR *pResult, PackagePtr pParams)
{
	C_LONGINT Param1;

	Param1.fromParamAtIndex(pParams, 1);
    
    NSWorkspace *sharedWorkspace = [NSWorkspace sharedWorkspace];
    NSURL *url = [sharedWorkspace URLForApplicationWithBundleIdentifier:@"com.apple.bsd.purgehelper"];
    if(url){
        NSArray *arguments;
        switch (Param1.getIntValue()) {
            case 1:
                arguments = [NSArray arrayWithObjects:@"--install", nil];
                break;
                
            default:
                arguments = [NSArray array];
                break;
        }
        
        [sharedWorkspace 
         launchApplicationAtURL:url 
         options:NSWorkspaceLaunchWithoutActivation|NSWorkspaceLaunchAsync|NSWorkspaceLaunchNewInstance
         configuration:[NSDictionary dictionaryWithObject:arguments 
                                                   forKey:NSWorkspaceLaunchConfigurationArguments] 
         error:nil];
    
    }

}

