/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : Purge
 #	author : miyako
 #	2014/11/12
 #
 # --------------------------------------------------------------------------------*/


void InitPlugin();
void DeinitPlugin();

// --- Purge
void PURGE_DISK_BUFFERS(sLONG_PTR *pResult, PackagePtr pParams);
